# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quiz
  pod 'Alamofire',  '~> 4.8.2'
  pod 'SwiftyJSON', '~> 5.0.0'

  target 'QuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
